// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBej_vP5QhY4MQSDs3_NSlRMjc3PtCey6E',
    appId: '1:1092602801595:web:2a66c5f43ea90cfa9fa89e',
    messagingSenderId: '1092602801595',
    projectId: 'flutterauthentication-f8cc1',
    authDomain: 'flutterauthentication-f8cc1.firebaseapp.com',
    storageBucket: 'flutterauthentication-f8cc1.firebasestorage.app',
    measurementId: 'G-KG41KD83N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl1RryDg-8l4wUO2rFAZmcfYhj9dIfv7w',
    appId: '1:1092602801595:android:9e26a3276e5c6b909fa89e',
    messagingSenderId: '1092602801595',
    projectId: 'flutterauthentication-f8cc1',
    storageBucket: 'flutterauthentication-f8cc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeoBfbv17KGkhbVjkaDyLUs-Lpk2eLAcA',
    appId: '1:1092602801595:ios:1ffe732c885c80a19fa89e',
    messagingSenderId: '1092602801595',
    projectId: 'flutterauthentication-f8cc1',
    storageBucket: 'flutterauthentication-f8cc1.firebasestorage.app',
    iosBundleId: 'com.example.flutterauthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeoBfbv17KGkhbVjkaDyLUs-Lpk2eLAcA',
    appId: '1:1092602801595:ios:1ffe732c885c80a19fa89e',
    messagingSenderId: '1092602801595',
    projectId: 'flutterauthentication-f8cc1',
    storageBucket: 'flutterauthentication-f8cc1.firebasestorage.app',
    iosBundleId: 'com.example.flutterauthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBej_vP5QhY4MQSDs3_NSlRMjc3PtCey6E',
    appId: '1:1092602801595:web:1e39d471d59a76409fa89e',
    messagingSenderId: '1092602801595',
    projectId: 'flutterauthentication-f8cc1',
    authDomain: 'flutterauthentication-f8cc1.firebaseapp.com',
    storageBucket: 'flutterauthentication-f8cc1.firebasestorage.app',
    measurementId: 'G-CYRD891R2M',
  );
}
